### ISSUE TITLE
[BUG] Unexpected empty search results

### ISSUE THREAD

**Issue by tg111** [tatsuz0u/EhPanda#14] opened 2021-05-30 05:19 UTC
已经开翻墙了。只有搜索页和标签搜索打不开
![A13AF97C-9C8E-4819-9606-86DFA869F024](https://user-images.githubusercontent.com/45155511/120092985-af22d100-c149-11eb-9678-8cc017d827eb.png)

![0861B409-ABC0-4BE1-9AFC-6912F953A993](https://user-images.githubusercontent.com/45155511/120093027-f4df9980-c149-11eb-92fe-78d6aff01978.png)

**Comment by tatsuz0u** [comment] 2021-06-06 02:25
您好，

經測試female: yuri是有數據的，而您的螢幕截圖顯示的錯誤信息為無數據，推測是出現了一些解析器未能預判的頁面，例如重定向。

感謝您的反饋，問題信息已被記錄。

**Comment by tatsuz0u** [comment] 2021-08-11 11:15
I'm closing this issue since this unexpected behavior is unreproducible and this part of codes have been changed a lot.

**Closed by tatsuz0u** 2021-08-11 11:15 UTC
Labels: bug
