### ISSUE TITLE
[BUG] iphone12 mini could not connect exhentai，but can connect e-hentai

### ISSUE THREAD

**Issue by CN-JohnYoung** [tatsuz0u/EhPanda#178] opened 2021-11-19 10:53 UTC
**Describe the bug**
IPhone 12 mini, IOS 15.1. 切到e-hentai时候4G与wifi都能直连，切到exhentai时候无论挂不挂vpn，4G与wifi都显示：发生网络故障请稍后再试。

**To Reproduce**
1. Go to '设置-账户'
2. Click on 'ExHentai'
3. Scroll down to '主页'

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 15]
 - App Version [e.g. 1.0.3]

**Additional context**

**Comment by CN-JohnYoung** [comment] 2021-11-19 10:55
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Please complete the following information:**
> 
> * Device: [e.g. iPhone 12]
> * OS: [e.g. iOS 15]
> * App Version [e.g. 1.0.3]
> 
> **Additional context** Add any other context about the problem here.

**Comment by tatsuz0u** [comment] 2021-11-19 11:08
In `Setting - Account - ExHentai`, are those three fields all filled with valid cookies?
Did you turn `Bypass SNI Filtering` feature on? If so, can you turn it off and try again? If you're living in a country that E-Hentai has been banned there, consider using a proxy instead. 

Please describe what you actually see when you try to access ExHentai. And make sure your IP hasn't been banned by E-Hentai, so as your account.

**Comment by tatsuz0u** [comment] 2021-11-21 15:48
`I am going to close this issue since it's unreproducible and the issuer is not responding.`

**Closed by tatsuz0u** 2021-11-21 15:48 UTC
