### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tyrzax** [tatsuz0u/EhPanda#165] opened 2021-10-28 11:04 UTC
**Describe the bug**
Searching is not working, always shows "There seems to be nothing here", as well as Watched.
Front page, Popular page and Favorite tab are showing contents as intended.

**To Reproduce**
Simply search anything. 
Or go into Watched tab.
e.g.: 
![IMG_DD27F26990A7-1](https://user-images.githubusercontent.com/87009977/139242679-7eaa5228-79b8-49e1-ba47-4ea8cfc472e3.jpeg)
![IMG_4551](https://user-images.githubusercontent.com/87009977/139243530-fa618f74-e6d4-413a-b301-4ff239038701.PNG)

**Expected behavior**
Well, it should show something.

 - Device: iPhone Xs
 - OS: iOS 15.0.2
 - App Version 1.3.7

**Comment by tatsuz0u** [comment] 2021-11-03 05:34
I am going to close this issue since it's unreproducible and the issuer is not responding.

**Closed by tatsuz0u** 2021-11-03 05:34 UTC
